
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/community;AUTO_SERVER=TRUE
    username: sa
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
